name: Build and Push Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for workload identity federation
      contents: write  # Required for updating files in the repository

    steps:
      # Checkout the source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate with GCP using workload identity federation
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/142680795577/locations/global/workloadIdentityPools/kodiak-pool-new/providers/github-oidc-provider'
          service_account: 'kodiac-svc-acc@kodiak-448212.iam.gserviceaccount.com'
          token_format: 'access_token'
          create_credentials_file: true
          cleanup_credentials: true

      # Set up Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # Set Docker image version using GitHub Run Number
      - name: Set Docker image version
        id: version
        run: echo "VERSION=v1.${{ github.run_number }}" >> $GITHUB_ENV

      # Build and Push Docker Image to GCP Container Registry
      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/kodiak-448212/kodiak/kodi:${{ env.VERSION }} ./frontend
          docker push us-central1-docker.pkg.dev/kodiak-448212/kodiak/kodi:${{ env.VERSION }}

      # Update Kubernetes manifest
      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image: us-central1-docker.pkg.dev/kodiak-448212/kodiak/kodi:.*|image: us-central1-docker.pkg.dev/kodiak-448212/kodiak/kodi:${{ env.VERSION }}|" package/manifests/frontend.yaml

      # Commit and push changes
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: package/manifests/frontend.yaml
          commit_message: "Update image version to ${{ env.VERSION }}"
          branch: main