name: Build and Push Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Add this line to ensure the GITHUB_TOKEN has the required permissions for workload identity federation

    steps:
      # Checkout the source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate with GCP using workload identity federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/448212/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "my-service-account@kodiak-448212.iam.gserviceaccount.com"

      # Configure Docker to use the GCP Container Registry
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      # Set Docker image version using GitHub Run Number
      - name: Set Docker image version
        id: version
        run: echo "VERSION=v1.${{ github.run_number }}" >> $GITHUB_ENV

      # Build and Push Docker Image to GCP Container Registry
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/kodiak-448212/kodi:${{ env.VERSION }} ./frontend
          docker push gcr.io/kodiak-448212/kodi:${{ env.VERSION }}

      # Update Kubernetes manifest in GitOps repository
      - name: Update Kubernetes manifest
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: https://github.com/your-org/kodi.git
          file_pattern: package/manifests/frontend.yaml
          commit_message: "Update image version to ${{ env.VERSION }}"
          branch: main
