name: Build and Push Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set the image version
      - name: Set Docker image version
        id: version
        run: echo "VERSION=v1.${{ github.run_number }}" >> $GITHUB_ENV

      # Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t alvin254/kodi:${{ env.VERSION }} .
          docker tag alvin254/kodi:${{ env.VERSION }} alvin254/kodi:latest
          docker push alvin254/kodi:${{ env.VERSION }}
          docker push alvin254/kodi:latest

      # Update Kubernetes manifest in GitOps repository
      - name: Update Kubernetes manifest
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: https://github.com/your-org/kodiak.git
          file_pattern: k8s/deployment.yaml
          commit_message: "Update image version to ${{ env.VERSION }}"
          branch: main
