name: Build and Push Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for workload identity federation

    steps:
      # Checkout the source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate with GCP using workload identity federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/448212/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "kodiac-svc-acc@kodiak-448212.iam.gserviceaccount.com"

      # Verify active Google Cloud account
      - name: Verify active account
        run: gcloud auth list

      # Configure Docker to use the GCP Container Registry
      - name: Configure Docker for Artifact Registry
        run: |
          echo "{\"credHelpers\":{\"gcr.io\":\"gcloud\",\"us.gcr.io\":\"gcloud\",\"eu.gcr.io\":\"gcloud\",\"asia.gcr.io\":\"gcloud\"}}" > ~/.docker/config.json

      # Set Docker image version using GitHub Run Number
      - name: Set Docker image version
        id: version
        run: echo "VERSION=v1.${{ github.run_number }}" >> $GITHUB_ENV

      # Build and Push Docker Image to GCP Container Registry
      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/kodiak-448212/kodiak/kodi:${{ env.VERSION }} ./frontend
          docker push us-central1-docker.pkg.dev/kodiak-448212/kodiak/kodi:${{ env.VERSION }}

      # Update Kubernetes manifest in GitOps repository
      - name: Update Kubernetes manifest
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: https://github.com/alvo254/kodi.git
          file_pattern: package/manifests/frontend.yaml
          commit_message: "Update image version to ${{ env.VERSION }}"
          branch: main
